name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: Backend
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster graphdatabasecluster \
            --service graphdatabaseservice \
            --force-new-deployment \
            --deployment-configuration "maximumPercent=200,minimumHealthyPercent=0"
